package fhc.cfm.com

dialect  "mvel"

rule "mid"
when
	$summary : MidsummaryCommand()
then
  System.out.println("mid rules init");

end

rule "question and answers print out"
when
	$q : Question()
then
  System.out.println("question Name : "+$q.name+":"+ $q.answer.value);
end 

rule "based on salary generate chart"
when
	$q_salary : Question(name=="salary")
	$q_age : Question(name=="age")
	$summary : Mid$summaryCommand()
then
	 
  age = $q_age.answer.value	 
  salary  = $q_salary.answer.value	
  
  $summary.titles = ['age','you','medium','top10']
  
  
  // age 0
  $summary.data.add([0, 0, 0 ,0])
  
  // age start from 18, increase 2
  foreach(i: 10){
		if(age < i){
			$summary.data.add([18+ i*2, 18000 + i*100, 20000 + i*200 ,3000 + i*300])
		}else{
			salary = salary + i*100
			$summary.data.add([18+ i*2, salary, 20000 + i*200 ,3000 + i*300])
		}
 }
 
 modify ( $summary ) 

end