import fhc.cfm.com.*;

dialect  "mvel"

rule "test"
when
then
  System.out.println("mid rules init test--------");
end

rule "mid"
when
	$summary : MidSummaryCommand()
then
  System.out.println("mid rules init");
end

rule "question and answers print out"
when
	$q : Question()
then
  System.out.println("question Name : "+$q.name+":"+ $q.answer.value);
end 

rule "based on salary generate chart"
when
	$q_salary : Question(name=="salary")
	$q_age : Question(name=="age")
	$summary : MidSummaryCommand()
then


  int age = $q_age.answer.value;
  salary  = $q_salary.answer.value;	
	
	System.out.println("question Name age : -----------"+age);
	System.out.println("question Name salary : -----------"+salary);	

  // age 0
  $summary.data.add(['age','you','medium','top10']);
  $summary.data.add([0, 0, 0 ,0]);
  age = 25
  // age start from 18, increase 2
	for (int i =0; i < 10; i++) { 
		$summary.data.add([18+ i*2, Integer.valueOf(salary)+i*100, 20000 + i*200 ,3000 + i*300]);
		/*
		if(age > 18+ i*2){
			System.out.println("**********************************"+(18+ i*2));
		}else{
			System.out.println("**********************************"+(18+ i*2));
			$summary.data.add([18+ i*2, Integer.valueOf(salary)+i*100, 20000 + i*200 ,3000 + i*300]);
		}
		*/		
	}  

end
