import fhc.cfm.com.*;

dialect  "mvel"

rule "test"
when
then
  System.out.println("mid rules init test--------");
end

rule "mid"
when
	$summary : MidSummaryCommand()
then
  System.out.println("mid rules init");
end


rule "final"
when
	$summary : FinalSummaryCommand()
then
  System.out.println("final rules init");
end

rule "question and answers print out"
when
	$q : Question()
then
  System.out.println("question Name : "+$q.name+":"+ $q.answer.value);
end 

rule "based on salary generate chart"
when
	$q_salary : Question(name=="salary")
	$q_age : Question(name=="age")
	$summary : MidSummaryCommand()
then

  // build chart data		
  int age = $q_age.answer.value;
  salary  = $q_salary.answer.value;	
	
	System.out.println("question Name age : -----------"+age);
	System.out.println("question Name salary : -----------"+salary);	

  // age 0
  $summary.chartData.add(['age','you','medium','top10']);
  $summary.chartData.add([0, 0, 0 ,0]);
  age = 25
  // age start from 18, increase 2
	for (int i =0; i < 10; i++) { 
		$summary.chartData.add([18+ i*2, Integer.valueOf(salary)+i*100, 20000 + i*200 ,3000 + i*300]);	
	}
	
	
	// build table data
	 $summary.tableData.add(['','YOU','MEDIAN','tOP 10%']);
	 
	 $summary.tableData.add(['Average income of your age group: ','$'+salary,'$75,201','$300,126']);
	 $summary.tableData.add(['Average saving of your age group: ','$'+salary,'$30,720','$150,816']);
	 $summary.tableData.add(['Average debt of your age group: ','$'+salary,'$2,611','$0']);
	 $summary.tableData.add(['Average lifetime earn: ','$'+salary*10,'$5,526,200','$32,610,010']); 
end
